### PR TITLE
Resource

### PR DESCRIPTION
**Pull request by Scrunshes**
Resource need to be bindable in order to be used by other components.

### CODE REVIEW

**Comment by RWOverdijk** [comment]
What other components are you talking about?

**Comment by Scrunshes** [comment]
Paginated or data-table will need to be able to give pagination the resource they are using which will be known through their own resource attribute.

**Comment by doktordirk** [comment]
can you seperate code changes from builds? makes it easier to read for me

**Comment by Scrunshes** [comment]
@doktordirk duly noted for next time :)

**Pull request merged**
